### ISSUE TITLE
Usernames only stay connected for about 30 seconds

### ISSUE THREAD

**Issue by msemple1111** [unixpickle/kahoot-hack#12]
When using the site [hackkahoot.xyz](http://hackkahoot.xyz), the usernames only stay connected for a limited time before being removed. This is probably because the connection for each user is not left open. 
I suspect it is the same for the command line utility but I am suffering from bug #9 so cannot test it - I would appreciate this being confirmed in the command line as well.

This could be fixed by keeping the connection open, continually connecting in a forever while loop; this would have to be done for each user.

**Comment by unixpickle** [comment]
I intentionally do this so that my server is not overloaded with outgoing connections--and so that it cannot be used to DOS kahoot.it. The flood tool itself stays connected until you kill it, as do most of the other tools. The `kahoot-rand` tool in particular is my favorite, because it not only stays connected but actually *answers* each question from every registered user.

**Comment by unixpickle** [comment]
It should be noted that my actual code does send keepalives correctly, at least as far as I have tested, so it will not be deauthenticated.
