### ISSUE TITLE
Kahoot Site POST Submission 

### ISSUE THREAD

**Issue by nomorecats** [unixpickle/kahoot-hack#23]
I have the site directory for the kahoot hack installed on my webserver. The problem is every time I submit it redirects to /hack of the root directory which is default for the index.html. I've tried many different files and paths but can't seem to get it to work

**Comment by MatSn0w** [comment]
You'll need a webhost which supports the Go language.

**Comment by nomorecats** [comment]
The web host is currently running go Lang, the back end of it is Apache, is there any type of change I can make for it.

**Comment by unixpickle** [comment]
I highly doubt you are setting this up the right way.

Go is not like PHP. With PHP, you can simply copy the source code into an Apache web root and everything will work swimmingly. This makes it easy to run PHP code on shared hosting (which I am guessing you are using).

With Go, you have to run the program in the background on your server, listening on some port. The program itself acts as a webserver. This is different from PHP, since PHP depends on some other webserver like Apache. With Go, the program itself listens for HTTP connections on a given port. If you want to incorporate this into other websites which are hosted by different programs (e.g. by Apache), then you must set up a reverse proxy such as Nginx.

To run this website, `cd` into the site's source folder and run `go run main.go <port>`, where `<port>` is some port number. This will launch a program that acts as its _own_ webserver, independent of Apache. So, for instance, if you ran it on your own computer on port `1337`, you could connect directly to `http://localhost:1337` in your browser and see the website.

This will most likely not work on a shared host, since shared hosts don't like customers opening ports. Even if it does work, it will not allow you to access the site using some subdirectory of your existing Apache-hosted website. At best, you will be able to get it on a subdomain by setting up some kind of reverse proxy.

**Comment by nomorecats** [comment]
Thanks for the support, I'm hosting my own server so mapping shouldn't be an issue for me to do
