### ISSUE TITLE
Failed to connect: websocket: bad handshake

### ISSUE THREAD

**Issue by Arccotangent** [unixpickle/kahoot-hack#29]
If I run kahoot-rand:
```
go run main.go 530496 ../names.txt
Terminate this program to stop the automatons...
failed to connect: websocket: bad handshake
exit status 1
```
I modified it to allow reading names from a file.
I am running on a Linux system, and I have tried this with and without a proxy.
This worked before, but won't right now for some reason.

**Comment by plebdev** [comment]
Also receiving this error. Tried it on my regular network and through torify. Hope Kahoot didn't get around to blocking the scripts' method of connecting.

**Comment by Arccotangent** [comment]
It now suddenly works??

```
go run main.go 637461 ../names.txt
Terminate this program to stop the automatons...
<SIGINT>
go run main.go 637461 getrekt 50
Terminate this program to stop the automatons...
```

Good thing, since one of my classes could be using it tomorrow!
I won't close the issue, though, as this could be temporary or only working for me.

**Comment by Arccotangent** [comment]
Scripts worked flawlessly 2 days ago, and I managed to get 400 bots into the game before the class freaked out and the teacher started a new game. Then I put 50 bots in the new game and one of them won with a perfect score!

This seems to be somewhat random, as it was having some difficulty in my school today but I kept trying and it eventually got through. It doesn't seem as if Kahoot is actively blocking the connections, but an error with the websocket library used by the scripts. Good thing it works now, and hopefully it stays that way, because they're probably going to use it again next week!

**Comment by Coler234** [comment]
Has anyone solved the problem besides it just working again for you somehow? I have a class this afternoon and I would like to run this. I was doing tests yesterday and it was working perfectly. I have tried using this using a VPN and I still get the `websocket: Bad handshake`

**Comment by Arccotangent** [comment]
I've found that the error is occurring at kahoot/conn.go line 48
I've tried increasing and decreasing the read/write buffers, I've noticed no change.

I have noticed that it connects to https://kahoot.it/cometd
When I visit that link in my web browser, I get an error 403 (Forbidden)

**Comment by EnderofGames** [comment]
"// ErrBadHandshake is returned when the server response to opening handshake is
// invalid.
var ErrBadHandshake = errors.New("websocket: bad handshake")

// NewClient creates a new client connection using the given net connection.
// The URL u specifies the host and request URI. Use requestHeader to specify
// the origin (Origin), subprotocols (Sec-WebSocket-Protocol) and cookies
// (Cookie). Use the response.Header to get the selected subprotocol
// (Sec-WebSocket-Protocol) and cookies (Set-Cookie).
//
// If the WebSocket handshake fails, ErrBadHandshake is returned along with a
// non-nil *http.Response so that callers can handle redirects, authentication,
// etc."

This comes from the client.go file supplied in 'gorilla/websocket'. Changing the "websocket: bad handshake" will change the error, as a double check that this identifies the error.

I don't know how much changing the Kahoot hack will be able to solve this problem. What I have found is that it seems to be on Kahoot's end. Changing networks, trying this at schools or home, seems to be just as random if it works.

**Comment by ElliotGluck** [comment]
I too believe this is an issue on Kahoot's end. Any networks I use to connect return the same error regardless of which game I connect to. LAN hosts as well as internet hosts fail to connect.

**Comment by Arccotangent** [comment]
I've found the problem. The protocol has changed, but I'm working on updating the scripts! It should be ready for use within the next few days.

**Comment by unixpickle** [comment]
The code is merged and works for me!

**Comment by EnderofGames** [comment]
Thanks, fix works great.

**Comment by ElliotGluck** [comment]
Thanks for the update, works great now.
