### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by mteverst** [unixpickle/kahoot-hack#3]
How would you go about using these? Are they SQL injections, or what?

**Comment by unixpickle** [comment]
They are not SQL injections; as far as I can tell, Kahoot does not use SQL.  They are programs which connect to the Kahoot server and pretend to be a regular client. They then either send corrupt data to the server or flood the server with requests.

The flood.go hack works by connecting to the server many times and doing a regular registration for a bunch of sequential usernames.

The crash.go hack works because of a bug in the Kahoot JavaScript code. It processes incoming data in a way which makes it possible to trigger a JavaScript exception from a remote client.

In order to run the programs, you will need to install and configure the Go programming language. See [https://golang.org/doc/install](https://golang.org/doc/install).
