### ISSUE TITLE
[QUESTION] - Automation

### ISSUE THREAD

**Issue by i1331442** [unixpickle/kahoot-hack#54]
Is there a way to start the GO program and use a code to start the hack? And if so, is there a method to make this automated, like if I develop a program (in VB.NET or in .bat) that will start the hack automatically?

**Comment by unixpickle** [comment]
I am not quite sure what you are asking. You could obviously run any of these commands from another program. Also, the repository includes a general API for interfacing with Kahoot, which you could invoke from another Go program.

However, the tools require a game pin in order to know what game to join. When a game starts that you want to "hack", you must somehow specify to some program the game pin you are using; there is just no reasonable way to do it.

**Comment by i1331442** [comment]
Hey...

**Comment by unixpickle** [comment]
Yes, obviously you can do that. You can launch any program you want programmatically. If you do not know how to run Go code in general, look up "running Golang" or something.

**Comment by i1331442** [comment]
Ok, thanks, but could you please do the life easier for me by providing me the code for that? It would mean a lot to me! :)
