### ISSUE TITLE
kahoot-rand doesn't work with more then 1 bot

### ISSUE THREAD

**Issue by GNUGradyn** [unixpickle/kahoot-hack#64]
Using only 1 bot works just fine (even in multiple TMUX panes at once), but doing more then 1 fails. Here's the error returned:

Entered with 2 bots.                                                                                                                                       
Terminate this program to stop the automatons...                                                                                                           
failed to connect: failed to create session: parse session challenge: invalid character '<' looking for beginning of value                                 
exit status 1

**Comment by unixpickle** [comment]
I cannot reproduce the problem on my end (kahoot-rand appears to work fine for me). I've seen that error before, but only when the game pin is incorrect, so make sure you had the correct game pin when you tried to connect with multiple bots. Other than that, I cannot suggest much to help since I cannot reproduce the error.

**Comment by lopy67** [comment]
having the same problem

**Comment by unixpickle** [comment]
Does the same issue happen when you try to use kahoot-flood rather than kahoot-rand?

**Comment by lopy67** [comment]
will test now

**Comment by lopy67** [comment]
big test : Last login: Fri Dec  2 10:02:02 on ttys001
Lachlans-Mac:~ lachie$ go run /Users/lachie/Documents/go/kahoot-rand/main.go 146850 gosney 2
Entered with 2 bots.
Terminate this program to stop the automatons...
failed to connect: failed to create session: could not defeat session challenge
exit status 1
Lachlans-Mac:~ lachie$ go run /Users/lachie/Documents/go/kahoot-rand/main.go 146850 gosney 1
Entered with 1 bots.
Terminate this program to stop the automatons...
failed to connect: failed to create session: could not defeat session challenge
exit status 1
Lachlans-Mac:~ lachie$ go run /Users/lachie/Documents/go/kahoot-flood/main.go 146850 2
open 2: no such file or directory
exit status 1
Lachlans-Mac:~ lachie$ go run /Users/lachie/Documents/go/kahoot-flood/main.go 146850 1
open 1: no such file or directory
exit status 1
Lachlans-Mac:~ lachie$

**Comment by unixpickle** [comment]
The kahoot-flood error is only because you are missing the nickname argument. When you don't specify "<pin> <nickname> <count>" as arguments, but rather "<pin> <other thing>", it treats <other thing> as a file and reads it for nicknames to join with. Add a nickname to the arguments to "kahoot-flood" and test again.

**Comment by lopy67** [comment]
yep... whoops.

Lachlans-Mac:~ lachie$ go run /Users/lachie/Documents/go/kahoot-flood/main.go 146850 gosney 10
failed to connect: failed to create session: parse session challenge: invalid character '<' looking for beginning of value
exit status 1
Lachlans-Mac:~ lachie$

**Comment by lopy67** [comment]
actually

6850 gosney 1
failed to connect: failed to create session: parse session challenge: invalid character '<' looking for beginning of value
exit status 1
Lachlans-Mac:~ lachie$

**Comment by unixpickle** [comment]
@lopy67 to help more, here's how you can get more information about the cause of the error.

Find the file called sessions.go, it should be in the kahoot/ directory. Insert this line right before line 40:

```go
fmt.Println(string(body))
```

The code in that area should now read

```go
if err := json.Unmarshal(body, &bodyObj); err != nil {
	if string(body) == "Not found" {
		return "", fmt.Errorf("game pin not found: %d", gamePin)
	}
	fmt.Println(string(body))
	return "", fmt.Errorf("parse session challenge: %s", err)
}
```

**Comment by lopy67** [comment]
i added that but nothing extra is happening

**Comment by unixpickle** [comment]
How about instead of `fmt.Println(string(body))` you make it `fmt.Println("body:", string(body))`. Now, you should in the very least see a printout of the word "body:" before the error message is displayed. Also, make sure you save the file and make sure you are editing the right copy of the file if you have multiple copies.

**Comment by lopy67** [comment]
i fixed it i just ran from /go/src/

**Comment by unixpickle** [comment]
Okay. Post the output here, or if it is large perhaps attach it as a .txt file.

**Comment by LordBunny** [comment]
You also can join my discord https://discord.gg/XUeandW I floodsfor you so you don't need a pc (The bot floods for you)
