### ISSUE TITLE
Solution to the current cypher problem.

### ISSUE THREAD

**Issue by memanlolz** [unixpickle/kahoot-hack#67]
So.. I've been following this project for quite a while, and I don't really know GOlang, so I've replicated it in java. I have successfully deciphered the current algo and can share my solution with you if you would like. I have the _.replace function as well as a fix to the console.log

**Comment by memanlolz** [comment]
<without using safeval.pw, as long as GO can run a form of js>

**Comment by unixpickle** [comment]
Go cannot run a form of JavaScript, that is why safeval is employed in the first place. Plus, hard-coding solutions to the challenges is not a long-term solution.

The aim of safeval is that, even when Kahoot changes their challenge, it will be trivial to keep the program working. If I hard-coded solutions to each challenge into kahoot-hack itself (as I originally did), I would receive too many pull requests on a day-to-day basis from people who forgot to upgrade.

By the way, the `_.replace` function is part of the [lodash](https://lodash.com) module. Getting `console.log` to work properly was simply a matter of introducing a dummy function on safeval's server.

I agree that having a local (rather than server-side) solution would be nice, but then the constant updating would be a pain. Rewriting the entirety of kahoot-hack in Node.js would probably be a start of a more permanent solution, but that would only be the beginning.

**Comment by memanlolz** [comment]
the _.replace function can be minified to 
`
text.replace(expr,func)
`
this, removing the requirement for the iodash module.

**Comment by unixpickle** [comment]
The lodash module should still be included. Soon enough, Kahoot will likely change their challenge again, and could quite possibly use a different API from lodash next time. By including all of the packages that Kahoot uses in safeval.pw, it is less likely that they will break it. That being said, I do suspect that Kahoot has been intentionally testing challenges on safeval to ensure that they break it. I will probably begin to monitor activity on the site a little more closely to attempt to catch them.

**Comment by memanlolz** [comment]
Hm... Why not make it so that safeval.pw needs some sort of token from your side?

That'd be pretty cool, Fighting their insecurity by preventing them from finding yours.

**Comment by unixpickle** [comment]
It would be very difficult to prevent them from testing their challenges on safeval, but it would still be interesting to catch them doing so (maybe by seeing their IP in a log).

All Kahoot needs to do is 1) introduce a new challenge, and 2) try using kahoot-hack to see if it works. There's no way to prevent them from performing that process without somehow making kahoot-hack "exclusive", which I do not plan on doing. What I will say is that, as the environment on safeval.pw becomes closer and closer to the environment in a browser, it will be difficult for Kahoot to break it (but I doubt they will have too much trouble).
