### ISSUE TITLE
How did this work before?

### ISSUE THREAD

**Issue by rycao18** [unixpickle/kahoot-hack#7]
Can the creator or someone explain how this works? By this I mean what line of code does what? I don't really know the GO language but I might be able to fix this if someone explains this. Also, how do you execute/run GO code?

**Comment by unixpickle** [comment]
I will not explain line-by-line how the program works because, unless you have a very good general knowledge of programming, such an undertaking would take months or maybe even years. Instead, I will explain at a high level how this works.

In order to implement this, I first reverse-engineered the protocol that Kahoot uses. When devices connect to Kahoot, they do so through WebSockets. Most modern browsers let you easily monitor and dump the exact data which is being transferred over WebSockets, so this step wasn't too hard.

In general, the "hacks" imitate a regular client. The flood "hack" simply connects to the kahoot server many times as if it were a normal client and registers many different nicknames. It is clear that a regular person with a laptop could do the exact same thing if they could open tabs and type nicknames fast enough.

The "crash" hack worked by exploiting a bug in Kahoot's client-side JavaScript code. Essentially, I could send a malformed response packet which caused an exception on all connected clients that saw the packet. This would result in the Kahoot quiz "crashing"--the next question would not appear and the site was rendered useless until it was refreshed.

If I were Kahoot, I would have fixed the exception bug by now. However, I see no reason why the flood hack should be broken. It is much more likely that the people saying it is broken simply don't understand how to run Go code.

**Comment by fishfishfish2104** [comment]
how do i use the flood hack when i use it this happens 
i type this to run flood.go go run flood.go
then it says this Enter game pin: 98299
then this Enter nickname: test
then this Enter count: 4
then this happens Registering test1 ...
Error: tls: oversized record received with length 20527
exit status 1

**Comment by unixpickle** [comment]
@fishfishfish2104 please see the note in the README, namely:

> **NOTE:** I have not maintained these tools for a while. I have heard reports that they are broken. If anybody wants to fix them, be my guest. But I do not intend to.

**Comment by unixpickle** [comment]
See issue #9
